### ISSUE TITLE
minting fcb identifiers for the recipes currently in the toc

### ISSUE THREAD

**Issue by proccaserra** [FAIRplus/w3id.org#1]
@robertgiessmann whenever you have a moment, please see https://github.com/FAIRplus/w3id.org/commit/23c4d899e3103d8b95af3f36cf41f33e007c3454

id assigned based on the latest TOC from top to bottom according to the order in which they appear (for better or worse).
doing so meant reassigning the w3id to a landing page different from the one you initially assigned.

**Comment by ghost** [comment]
hi @proccaserra , very much appreciated ; I was wondering a lot about the following: should we be pragmatic and just reassign the identifiers so they fit nicely to the current TOC? Or should we "play by the rules", and not reassign identifiers we already minted? 

I would like to opt for the second, and rather change the identifiers in the 3 recipes for which we already published identifiers (i.e. FCB000, 001, 002) . I think everything else would be leading to being a bad example. 

Agreed?

**Comment by proccaserra** [comment]
@robertgiessmann at this stage, we should be pragmatic. The sequence order is incidental and will disappear as we add more recipe in future releases. As for the reassignment, I was expecting your comment. Since those have not been advertised or reused....
Having said that, if you feel strongly about this, then reassign and correct the pages accordingly. Also note that only recipes will be given an identifier, not all pages on the book (e.g. intro, foreword, etc...).

**Comment by ghost** [comment]
@proccaserra , thanks for your understanding. I reassigned them.
